// Study journey with local drafts and final-only submission.
(async () => {
  const D = window.StudyDraft;
  const submission = window.StudySubmit.controller();
  const screen = document.querySelector('#study-screen');
  const workspace = document.querySelector('#workspace-shell');
  const progress = document.querySelector('#study-progress');
  const layout = document.querySelector('#journey-layout');
  const routes = ['/study', '/study/pre', '/study/tasks/T0', '/study/post', '/study/complete'];
  const sectionNames = ['progress.information', 'progress.pre', 'progress.tasks', 'progress.post', 'progress.review'];
  // Generated by scripts/irexplorer-research/build_content.py.
  const CONTENT_VERSION = "v0.11-preview-2";
  const WORKSPACE_KEY = `irexplorer.study.workspace.${CONTENT_VERSION}`;
  // Participant wording comes from the package's validated message catalogue (see study-messages.js).
  // Content loading and its failure use the bootstrap wording, since no verified catalogue need be
  // available then.
  const { BOOTSTRAP, escape: esc } = window.StudyMessages;
  let messages = null;
  const messageText = (key, params) => Object.hasOwn(BOOTSTRAP, key) ? BOOTSTRAP[key] : messages.text(key, params);
  const messageHtml = (key, params, codes) => Object.hasOwn(BOOTSTRAP, key) ? esc(BOOTSTRAP[key]) : messages.html(key, params, codes);
  // Marks the first use of each packaged glossary term in T0 prose with its compiled help text.
  let terms = { pattern: null, byMatch: new Map() };
  function glossary(entries) {
    if (!Array.isArray(entries) || entries.some(g => typeof g?.id !== 'string' || typeof g.match !== 'string' || !g.match || typeof g.text !== 'string')) throw Error('Unsupported glossary');
    const pattern = g => (/^\w/.test(g.match) ? '\\b' : '') + g.match.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + (/\w$/.test(g.match) ? '\\b' : '');
    return { pattern: entries.length ? new RegExp(`(${entries.map(pattern).join('|')})`, 'gi') : null,
      byMatch: new Map(entries.map(g => [g.match.toLowerCase(), g])) };
  }
  const termHelp = (text, seen) => (terms.pattern ? String(text).split(terms.pattern) : [String(text)]).map(term => {
    const entry = terms.byMatch.get(term.toLowerCase());
    if (!entry || seen.has(entry.id)) return esc(term);
    seen.add(entry.id);
    return `<span class="study-term-help" tabindex="0" role="term" data-help="${esc(entry.text)}">${esc(term)}</span>`;
  }).join('');
  const button = (action, key, primary = false) => `<button type="button" data-action="${action}"${primary ? ' class="primary"' : ''}>${messageHtml(key)}</button>`;
  const heading = html => `<h2 id="route-heading" tabindex="-1">${html}</h2>`;
  let content, store, draft = null, editingPre = false, errors = {}, loaded = false, loadError = false;
  let activeTask = null, clock = null, stopConfirming = false, returnFocusToStop = false;
  const answersFor = section => section.startsWith('T') ? draft.tasks[section].answers : draft[section];
  const outcome = status => ({ key: { completed: 'outcome.completed', skipped: 'outcome.skipped', could_not_work_out: 'outcome.unable', pending: 'outcome.pending' }[status] });
  const seconds = ms => (ms / 1000).toFixed(1);
  const interruption = t => t.interrupted ? { key: 'timing.interrupted' } : '';
  const taskRoute = () => '/study/tasks/' + D.currentTask(draft);
  const taskFor = id => content.tasks.find(task => task.id === id);
  const inherits = task => task?.entryWorkspace.inherit === 'previous';
  // A declared (non-inheriting) entry configuration in the workspace's own snapshot shape.
  const declaredEntry = ({ entryWorkspace: { example, left, right } }) => ({ exampleId: example, functionName: null,
    panels: { left: { ordinal: left.ordinal, viewType: left.view }, right: { ordinal: right.ordinal, viewType: right.view } } });
  // A task's workspace is kept for recovery when it, or the task after it, inherits.
  function carriesWorkspace(id) {
    const index = content.tasks.findIndex(task => task.id === id);
    return inherits(content.tasks[index]) || inherits(content.tasks[index + 1]);
  }
  function leaveTask(route) {
    if (!activeTask || route === '/study/tasks/' + activeTask) return;
    clock?.stop(true); save(); clock = null; activeTask = null;
  }
  function taskHtml(id) {
    const task = taskFor(id), record = draft.tasks[id];
    const locked = record.status !== 'pending';
    const open = matchMedia('(max-width: 1100px)').matches ? '' : ' open';
    const instructions = id === 'T0' ? (() => { const seen = new Set(); return content.taskIntroduction.map(p => `<p>${termHelp(p, seen)}</p>`).join('') + `<p class="task-prose">${termHelp(task.instructions, seen)}</p>`; })() : `<p class="task-prose">${esc(task.instructions)}</p>`;
    const complete = id === 'T0' ? 'actions.finish-orientation' : id === 'T6' ? 'actions.post' : 'actions.continue';
    return heading(messageHtml('task.title', { taskId: id, title: task.title })) + `<p class="eyebrow">${id === 'T0' ? messageHtml('task.orientation') : messageHtml('task.number', { taskNumber: id.slice(1) })}</p><p><strong>${messageHtml('task.goal-label')}</strong> ${esc(task.goal)}</p>
      <nav class="task-jumps" aria-label="${messageHtml('task.navigation')}"><a href="#task-instructions">${messageHtml('task.instructions')}</a><a href="#workspace-shell">${messageHtml('task.workspace-link')}</a><a href="#task-responses">${messageHtml('task.responses-link')}</a></nav>
      <details id="task-instructions" class="task-details"${open}><summary>${messageHtml('task.setup-title')}</summary>
      ${instructions}
      <p>${inherits(task) ? messageHtml('task.inherit') : messageHtml('task.entry', { example: task.entryWorkspace.example })}</p></details>
      <p id="task-timing" class="form-note" role="status"></p>${!locked ? button('pause-task', record.paused ? 'actions.resume' : 'actions.pause') : ''}<div id="task-responses" class="task-responses panel">
      <details class="task-details task-responses-details"${open}><summary>${messageHtml(locked ? 'task.responses-locked' : 'task.responses-open')}</summary>
      <a href="#route-heading">${messageHtml('task.goal-link')}</a><p>${locked ? messageHtml('task.locked', { outcome: outcome(record.status) }) : messageHtml('task.optional')}</p>
      <form id="survey-form" data-section="${id}" novalidate><p id="form-errors" role="alert" tabindex="-1"></p><fieldset class="task-inputs"${locked ? ' disabled' : ''}>
      ${D.fieldsFor(content, id).map(field => fieldHtml(field, id)).join('')}
      </fieldset>${!locked ? `<div class="screen-actions"><button type="submit" class="primary task-complete">${messageHtml(complete)}</button>${id !== 'T0' ? button('unable-task', 'actions.unable') + button('skip-task', 'actions.skip') : ''}</div>` : ''}</form></details>
      <nav class="task-history" aria-label="${messageHtml('task.progress')}">${content.tasks.map(t => draft.tasks[t.id].status !== 'pending' ? `<a href="#/study/tasks/${t.id}">${messageHtml('task.saved', { taskId: t.id })}</a>` : t.id === D.currentTask(draft) ? `<a href="#${taskRoute()}">${messageHtml('task.current', { taskId: t.id })}</a>` : `<span>${esc(t.id)}</span>`).join(' ')}</nav>
      ${locked ? `<a href="#${D.tasksComplete(draft) ? '/study/post' : taskRoute()}">${messageHtml('actions.current')}</a>` : ''}</div>`;
  }
  function updateTaskStatus() {
    if (!activeTask || !draft) return;
    const t = draft.tasks[activeTask], status = layout.querySelector('#task-timing');
    if (!status) return;
    status.textContent = t.status !== 'pending' ? messageText('timing.saved', { seconds: seconds(t.durationMs), interrupted: interruption(t) }) : messageText(t.paused ? 'timing.paused' : 'timing.active');
    const pause = layout.querySelector('[data-action="pause-task"]');
    if (pause) { pause.textContent = messageText(t.paused ? 'actions.resume' : 'actions.pause'); pause.disabled = !t.presented; }
    const inputs = layout.querySelector('.task-inputs');
    if (inputs) inputs.disabled = t.status !== 'pending' || !t.presented || t.paused;
    const complete = layout.querySelector('.task-complete');
    if (complete) complete.disabled = t.status !== 'pending' || !t.presented || t.paused;
    for (const action of layout.querySelectorAll('[data-action="skip-task"], [data-action="unable-task"]')) action.disabled = t.status !== 'pending' || t.paused;
  }
  function startClock() {
    if (!activeTask || !draft) return;
    const t = draft.tasks[activeTask];
    if (t.status !== 'pending') return;
    t.presented = true;
    if (!document.hidden && !t.paused) clock?.resume();
    save(); updateTaskStatus();
  }
  function enterTask(id) {
    if (activeTask === id) { updateTaskStatus(); return; }
    activeTask = id; draft.p13Locked = true; save();
    const t = draft.tasks[id]; clock = window.TaskClock(t);
    if (t.status === 'pending') {
      startClock();
      const task = taskFor(id), inherit = inherits(task);
      window.StudyWorkspace.prepareTask(inherit ? readWorkspaceSnapshot() : declaredEntry(task), { inherit });
    }
    updateTaskStatus();
  }
  function finishTask(id, status) {
    if (!id || !draft || !available()) return;
    const t = draft.tasks[id];
    if (t.status !== 'pending' || t.paused || !t.presented || (id === 'T0' && status !== 'completed')) return;
    errors = D.validate(content, id, t.answers, true);
    if (Object.keys(errors).length) { showErrors(); layout.querySelector('[aria-invalid="true"]')?.focus(); return; }
    clock?.stop(); t.status = status; t.paused = false; save();
    if (available()) go(D.tasksComplete(draft) ? '/study/post' : taskRoute()); else updateTaskStatus();
  }
  function taskReview() {
    return `<details class="response-review"><summary>${messageHtml('review.tasks')}</summary><ul>${content.tasks.map(task => { const t = draft.tasks[task.id]; return `<li><a href="#/study/tasks/${task.id}">${messageHtml('review.task-summary', { taskId: task.id, outcome: outcome(t.status), seconds: seconds(t.durationMs), interrupted: interruption(t) })}</a></li>`; }).join('')}</ul><p>${messageHtml('review.duration')}</p></details>`;
  }
  function stopControls() {
    if (!stopConfirming) return button('stop', 'actions.stop');
    // The confirmation's leading question stays emphasised, as before its wording moved to the catalogue.
    const [, question, rest] = /^(.*?[?.!])(\s.*)?$/s.exec(messageText('discard.confirm')) || [null, messageText('discard.confirm'), ''];
    return `<div class="stop-confirmation" role="alert"><p><strong>${esc(question)}</strong>${esc(rest || '')}</p><div class="screen-actions">${button('cancel-stop', 'actions.keep')}<button type="button" class="destructive" data-action="confirm-stop">${messageHtml('actions.discard')}</button></div></div>`;
  }
  document.addEventListener('workspace-ready', () => { saveWorkspaceSnapshot(); updateTaskStatus(); });
  document.addEventListener('visibilitychange', () => {
    if (!clock) return;
    if (document.hidden) { clock.stop(true); save(); } else startClock();
  });
  window.addEventListener('pagehide', () => { if (clock) { clock.stop(true); save(); } });
  window.addEventListener('pageshow', () => { if (clock) startClock(); });
  setInterval(() => { if (clock?.running) { clock.checkpoint(); save(); } }, 1000);
  function go(route, replace = false) {
    if (replace || location.hash === `#${route}`) { history.replaceState(null, '', `#${route}`); render(); }
    else location.hash = route;
  }
  function maximum() { if (submission.state) return 4; return !draft ? 0 : !draft.preComplete ? 1 : !D.tasksComplete(draft) ? 2 : !draft.reviewReady ? 3 : 4; }
  function save() { if (draft) store.save(draft); updateStorage(); }
  function readWorkspaceSnapshot() {
    try {
      const stored = JSON.parse(sessionStorage.getItem(WORKSPACE_KEY) || 'null');
      return stored?.contentVersion === content.contentVersion ? stored.workspace : null;
    } catch { return null; }
  }
  function saveWorkspaceSnapshot() {
    if (!activeTask || !carriesWorkspace(activeTask)) return;
    const workspaceSnapshot = window.StudyWorkspace.snapshot();
    if (!workspaceSnapshot) return;
    try { sessionStorage.setItem(WORKSPACE_KEY, JSON.stringify({ contentVersion: content.contentVersion, workspace: workspaceSnapshot })); }
    catch { /* Workspace recovery is best effort; study answers remain in their own draft. */ }
  }
  function updateStorage() {
    const area = screen.querySelector('#draft-status');
    if (submission.state) { if (area) area.hidden = true; return; }
    if (!area || !store) return;
    const signature = [store.mode, store.issue?.key, store.stale, store.unreadable, !!draft].join('|');
    if (area.dataset.signature === signature) return;
    area.dataset.signature = signature;
    area.classList.toggle('storage-ok', store.mode === 'local');
    if (store.mode === 'blocked' || store.mode === 'invalid') {
      area.innerHTML = `<p role="alert">${messageHtml(store.issue)}${store.stale ? messageHtml('storage.stale') : ''}</p>${draft ? button('retry-storage', 'actions.retry-save') : ''}${!store.stale && store.mode !== 'invalid' ? button('memory', 'actions.memory') : ''}${store.stale ? button('stop', 'actions.retry-discard') : ''}`;
    } else area.innerHTML = `<p role="status">${store.mode === 'memory' ? messageHtml('storage.memory') + (store.unreadable ? messageHtml('storage.unreadable') : '') : messageHtml(draft ? 'storage.saved' : 'storage.before-consent')}</p>`;
  }
  function available() { if (store.mode === 'local' || store.mode === 'memory') return true; screen.querySelector('#draft-status')?.focus(); return false; }
  function fieldHtml(field, section) {
    const answer = answersFor(section)[field.id], id = field.id.replaceAll('.', '-');
    const locked = section.startsWith('T') ? draft.tasks[section].status !== 'pending' : section === 'pre' && ((draft.preComplete && !editingPre) || (field.id === 'P13' && draft.p13Locked));
    const label = `${field.id}. ${field.prompt}`;
    const controlHint = field.presentation.control;
    let control;
    if (controlHint === 'textarea') control = `<label class="sr-only" for="answer-${id}">${esc(label)}</label><textarea id="answer-${id}" name="${field.id}" rows="3" aria-describedby="note-${id} error-${id}"${locked ? ' readonly' : ''}>${esc(answer.status === 'answered' ? answer.value : '')}</textarea>`;
    else if (controlHint === 'input') control = `<label class="sr-only" for="answer-${id}">${esc(label)}</label><input id="answer-${id}" type="text" name="${field.id}" value="${esc(answer.status === 'answered' ? answer.value : '')}" aria-describedby="note-${id} error-${id}"${locked ? ' readonly' : ''}>`;
    else if (controlHint === 'select') {
      const options = field.options.map(o => ({ ...o, status: field.optionStatuses?.[o.value] || 'answered' }));
      control = `<label class="sr-only" for="answer-${id}">${esc(label)}</label><select id="answer-${id}" name="${field.id}" aria-describedby="note-${id} error-${id}"${locked ? ' disabled' : ''}><option value="">${messageHtml('field.choose')}</option>${options.map(o => `<option value="${o.value}" data-status="${o.status}"${answer.status === o.status && (o.status !== 'answered' || answer.value === o.value) ? ' selected' : ''}>${esc(o.label)}</option>`).join('')}</select>`;
    }
    else {
      const options = (field.options || content.scales[field.scale]).map(o => ({ ...o, status: field.optionStatuses?.[o.value] || 'answered' }));
      if (field.notApplicableLabel) options.push({ value: 'na', status: 'not_applicable', label: field.notApplicableLabel });
      control = `<div class="answer-options${field.type === 'rating' ? ' rating-options' : ''}">${options.map((o, n) => {
        const selected = o.status !== 'answered' ? answer.status === o.status : answer.status === 'answered' && (Array.isArray(answer.value) ? answer.value.includes(o.value) : answer.value === o.value);
        const inputType = ['checkbox', 'checkboxes'].includes(controlHint) ? 'checkbox' : 'radio';
        return `<label class="answer-option${o.status === 'not_applicable' ? ' not-applicable' : ''}" for="answer-${id}-${n}"><input id="answer-${id}-${n}" type="${inputType}" name="${field.id}" value="${o.value}" data-status="${o.status}"${selected ? ' checked' : ''}${locked ? ' disabled' : ''}${field.required ? ' required' : ''} aria-describedby="note-${id} error-${id}"><span>${field.type === 'rating' && o.status === 'answered' ? `<span class="rating-number">${o.value}</span>` : ''}${esc(o.label)}</span></label>`;
      }).join('')}</div>`;
    }
    const note = locked ? messageHtml(field.id === 'P13' ? 'locking.expectation' : section.startsWith('T') ? 'locking.task' : 'locking.background') : ['text', 'short_text'].includes(field.type) ? messageHtml('field.text-limit', { required: { key: field.required ? 'field.required-label' : 'field.optional-label' }, maxLength: field.maxLength.toLocaleString() }) : messageHtml(field.required ? 'field.required' : field.type === 'multiple' ? 'field.multiple' : 'field.optional');
    return `<fieldset class="survey-item" data-field="${field.id}" data-field-type="${field.type}"${D.visible(field, answersFor(section)) ? '' : ' hidden'}><legend>${esc(label)}</legend><p id="note-${id}" class="form-note">${note}</p>${control}${field.inabilityLabel && !locked ? `<label class="answer-option"><input type="checkbox" name="${field.id}" data-inability="true"${answer.status === 'could_not_work_out' ? ' checked' : ''}>${esc(field.inabilityLabel)}</label>` : ''}${field.inabilityLabel && locked && answer.status === 'could_not_work_out' ? `<p>${esc(field.inabilityLabel)}</p>` : ''}<p id="error-${id}" class="field-error" role="alert"></p>${!locked && !['text', 'short_text'].includes(field.type) ? `<button type="button" class="clear-answer" data-clear="${field.id}" aria-label="${messageHtml('field.clear-accessible', { fieldId: field.id })}">${messageHtml('field.clear-label')}</button>` : ''}</fieldset>`;
  }
  function survey(section) {
    const sections = content[section === 'pre' ? 'preSections' : 'postSections'];
    return `<form id="survey-form" novalidate data-section="${section}"><p id="form-errors" role="alert" tabindex="-1"></p>${sections.map(s => `<section class="survey-section"><h3>${esc(s.title)}</h3>${s.intro ? `<p>${esc(s.intro)}</p>` : ''}${s.groups ? s.groups.map(g => `<h4>${esc(g.title)}</h4>${g.fields.map(id => fieldHtml(content.fields.find(f => f.id === id), section)).join('')}`).join('') : s.fields.map(id => fieldHtml(content.fields.find(f => f.id === id), section)).join('')}</section>`).join('')}<div class="screen-actions"><button type="submit" class="primary">${messageHtml(section === 'post' ? 'actions.review' : editingPre ? 'actions.pre-corrections' : draft.preComplete ? 'actions.return-tasks' : 'actions.pre-start')}</button>${section === 'pre' && draft.preComplete && !editingPre ? button('edit-pre', 'actions.edit-pre') : ''}</div></form>`;
  }
  function informationSections(sections) {
    return sections.map(s => `<section><h3>${esc(s.title)}</h3>${s.blocks.filter(b => !['study-purpose', 'submission-guidance'].includes(b.role)).map(b => b.kind === 'paragraph' ? `<p>${esc(b.text)}</p>` : `<${b.kind === 'ordered' ? 'ol' : 'ul'}>${b.items.map(i => `<li>${esc(i)}</li>`).join('')}</${b.kind === 'ordered' ? 'ol' : 'ul'}>`).join('')}</section>`).join('');
  }
  function info() {
    const blocks = content.information.flatMap(section => section.blocks);
    const purpose = blocks.find(block => block.role === 'study-purpose');
    const submissionGuidance = blocks.find(block => block.role === 'submission-guidance');
    const consentFields = D.fieldsFor(content, 'consent');
    return `${purpose ? `<p class="study-purpose"><strong>${messageHtml('information.purpose-label')}</strong> ${esc(purpose.text)}</p>` : ''}${submissionGuidance ? `<p class="submission-guidance" role="note"><strong>${messageHtml('information.submission-label')}</strong> ${esc(submissionGuidance.text)}</p>` : ''}<div class="participant-information">${informationSections(content.information)}</div><h3>${messageHtml('consent.title')}</h3><p>${messageHtml('consent.introduction')}</p><p>${messageHtml('consent.local')}</p>${consentFields.map(f => `<label class="acknowledgement" for="${f.id}"><input id="${f.id}" type="checkbox"${draft ? ' checked disabled' : ''}>${esc(f.prompt)}</label>`).join('')}<p id="consent-error" role="alert"></p><div class="screen-actions">${button('start', draft ? 'actions.return' : 'actions.start', true)}${!draft ? button('decline', 'actions.decline') : ''}</div>`;
  }
  function review() {
    const answerText = (f, a) => a.status === 'not_applicable' ? (f.notApplicableLabel ? esc(f.notApplicableLabel) : messageHtml('answer.not-applicable'))
      : a.status === 'answered' ? esc(['text', 'short_text'].includes(f.type) ? a.value : (Array.isArray(a.value) ? a.value : [a.value]).map(v => (f.options || content.scales[f.scale]).find(o => o.value === v).label).join('; '))
      : messageHtml('answer.unanswered');
    return heading(messageHtml('review.title')) + (submission.issue ? `<p role="alert">${messageHtml(submission.issue)}</p>` : '') + `<p><strong>${messageHtml('review.not-submitted')}</strong> ${messageHtml('review.submit-detail')}</p><p>${messageHtml('review.frozen')}</p><p>${messageHtml('review.editable')}</p><div class="screen-actions">${button('edit-pre', 'actions.edit-pre')}<a href="#/study/post">${messageHtml('actions.edit-post')}</a>${content.submissionEnabled ? button('submit-responses', 'actions.submit', true) : `<button disabled>${messageHtml('actions.disabled')}</button>`}</div>${taskReview()}${['pre', 'post'].map(section => `<details class="response-review"><summary>${messageHtml('review.section-answers', { section: { key: section === 'pre' ? 'progress.pre' : 'progress.post' } })}</summary><dl>${D.fieldsFor(content, section).filter(f => D.visible(f, draft[section])).map(f => `<dt>${esc(f.id + '. ' + f.prompt)}</dt><dd>${answerText(f, draft[section][f.id])}</dd>`).join('')}</dl></details>`).join('')}`;
  }
  function submissionHtml() {
    const state = submission.state, issue = submission.issue ? `<p role="alert">${messageHtml(submission.issue)}</p>` : '';
    if (state.kind === 'receipt') return heading(messageHtml('receipt.title')) + `<p>${messageHtml('receipt.saved')}</p><p>${messageHtml('receipt.code', { receiptId: state.receipt.receiptId }, ['receiptId'])}</p><p>${messageHtml('submission.participant-code', { participantCode: state.receipt.participantCode }, ['participantCode'])}</p><p>${messageHtml('receipt.keep')}</p>${submission.issue ? `${issue}${button('cleanup-receipt', 'actions.cleanup')}` : `<p>${messageHtml('cleanup.done')}</p>${button('new-study', 'actions.new-session')}`}`;
    return heading(messageHtml(submission.busy ? 'submission.submitting' : 'submission.unconfirmed')) + `<p role="status">${messageHtml(submission.busy ? 'submission.wait' : 'submission.retry')}</p><p>${messageHtml('submission.participant-code', { participantCode: state.submission.participantCode }, ['participantCode'])}</p>${issue}${submission.busy ? '' : button('retry-submit', 'actions.retry-submit', true)}<p>${messageHtml('submission.keep-tab')}</p>`;
  }
  function render() {
    const oldResponses = layout.querySelector('#task-responses');
    if (oldResponses?.parentNode) oldResponses.parentNode.removeChild(oldResponses);
    const route = location.hash.slice(1) || '/explore', explore = route === '/explore';
    if (loaded && submission.state && !explore && route !== '/study/complete') return go('/study/complete', true);
    leaveTask(route);
    const exited = ['/study/declined', '/study/stopped'].includes(route);
    const requestedTask = /^\/study\/tasks\/(T[0-6])$/.exec(route)?.[1];
    const index = requestedTask ? 2 : routes.indexOf(route);
    if (loaded && draft?.preComplete && requestedTask && Number(requestedTask.slice(1)) > Number(D.currentTask(draft).slice(1))) return go(taskRoute(), true);
    if (loaded && !explore && !exited && (index < 0 || index > maximum())) return go(maximum() === 2 ? taskRoute() : routes[maximum()], true);
    screen.hidden = explore; workspace.hidden = !explore && (!loaded || index !== 2);
    progress.hidden = explore || exited || !loaded;
    document.querySelector('#explore-heading').hidden = !explore;
    document.querySelector('.skip-link').href = explore ? '#explore-heading' : '#route-heading';
    layout.classList.toggle('with-task', !explore && loaded && index === 2);
    if (explore) { window.StudyWorkspace.clearManualSetup(); document.title = 'Explore · irexplorer'; document.querySelector('#explore-heading').focus(); return; }
    if (!loaded) {
      screen.innerHTML = heading(messageHtml(loadError ? 'load.unavailable' : 'load.loading')) + (loadError ? `<p>${messageHtml('load.retry')}</p>${button('retry-content', 'actions.retry-content', true)}` : '');
    } else {
      progress.setAttribute('aria-label', messageText('progress.sections'));
      progress.innerHTML = `<ol>${sectionNames.map((name, n) => `<li${n === index ? ' aria-current="step"' : ''}>${n + 1}. ${n <= maximum() ? `<a href="#${n === 2 && draft ? taskRoute() : routes[n]}">${messageHtml(name)}</a>` : messageHtml(name)}</li>`).join('')}</ol>`;
      let html;
      if (submission.state) html = submissionHtml();
      else if (submission.recoveryBlocked) html = heading(messageHtml('recovery.title')) + `<p role="alert">${messageHtml(submission.issue)}</p>${submission.legacyPending ? `<p>${messageHtml('recovery.server-copy')}</p>${submission.legacyParticipantCode ? `<p>${messageHtml('submission.participant-code', { participantCode: submission.legacyParticipantCode }, ['participantCode'])}</p>` : ''}${button('discard-incompatible-submission', 'actions.discard-incompatible')}` : `${button('retry-content', 'actions.retry-recovery')}<p>${messageHtml('recovery.memory')}</p>${button('memory', 'actions.memory')}`}`;
      else if (exited) html = heading(messageHtml(route.endsWith('declined') ? 'discard.declined' : 'discard.stopped')) + `<p>${messageHtml('discard.done')}</p>${button('restart', 'actions.restart', true)} <a href="#/explore">${messageHtml('actions.explore')}</a>`;
      else if (index === 0) html = heading(messageHtml('information.title')) + info();
      else if (index === 1) html = heading(messageHtml('pre.title')) + `<p>${esc(content.journey.introductions.pre)}</p><p>${messageHtml(draft.p13Locked ? 'pre.locked' : 'pre.lock-pending')}</p>` + survey('pre');
      else if (index === 2) html = taskHtml(requestedTask);
      else if (index === 3) html = heading(messageHtml('post.title')) + `<p>${esc(content.journey.introductions.post)}</p>` + survey('post');
      else html = review();
      screen.innerHTML = (!exited ? html.replace('</h2>', '</h2><div id="draft-status" class="draft-status" tabindex="-1"></div>') : html) + (draft && !exited && !submission.state ? `<p class="participant-code">${messageHtml('submission.participant-code', { participantCode: draft.participantCode })}</p><div class="study-utilities"><a href="#/study">${messageHtml('progress.information')}</a>${stopControls()}</div>` : '');
      const taskResponses = screen.querySelector('#task-responses');
      if (taskResponses?.id === 'task-responses') layout.append(taskResponses);
      updateStorage(); showErrors();
      if (index === 2) enterTask(requestedTask);
    }
    document.title = `${screen.querySelector('h2').textContent} · irexplorer`;
    screen.querySelector('h2').focus({ preventScroll: true });
    if (stopConfirming) screen.querySelector('[data-action="confirm-stop"]')?.focus();
    else if (returnFocusToStop) { screen.querySelector('[data-action="stop"]')?.focus(); returnFocusToStop = false; }
    // The desktop task sidebar scrolls independently of the page. Reset both
    // explicitly rather than relying on a browser's focus-scroll behaviour.
    screen.scrollTop = 0;
    screen.scrollLeft = 0;
    window.scrollTo(0, 0);
  }
  function showErrors() {
    for (const fieldset of layout.querySelectorAll('[data-field]')) {
      const error = errors[fieldset.dataset.field], message = error ? messageText(error) : '';
      fieldset.querySelector('.field-error').textContent = message;
      fieldset.querySelectorAll('input, textarea, select').forEach(e => e.setAttribute('aria-invalid', message ? 'true' : 'false'));
    }
    const summary = layout.querySelector('#form-errors');
    if (summary) summary.textContent = Object.keys(errors).length ? messageText('validation.summary') : '';
  }
  function updateAnswer(event) {
    const input = event.target, form = input.closest('#survey-form');
    if (!form || !draft || !input.name) return;
    const section = form.dataset.section, field = content.fields.find(f => f.id === input.name);
    if (!field || (section.startsWith('T') && (draft.tasks[section].status !== 'pending' || !draft.tasks[section].presented || draft.tasks[section].paused)) || (section === 'pre' && ((draft.preComplete && !editingPre) || (field.id === 'P13' && draft.p13Locked)))) return;
    if (input.dataset.inability) { answersFor(section)[field.id] = input.checked ? { status: 'could_not_work_out', value: null } : D.blank(); const textControl = input.closest('fieldset').querySelector('input[type="text"], textarea'); if (textControl) textControl.value = ''; }
    else if (['text', 'short_text'].includes(field.type)) answersFor(section)[field.id] = input.value.trim() ? { status: 'answered', value: input.value } : D.blank();
    else if (field.presentation.control === 'select') {
      if (event.type !== 'change') return;
      const status = input.selectedOptions[0].dataset.status;
      answersFor(section)[field.id] = status ? { status, value: status === 'answered' ? Number(input.value) : null } : D.blank();
    }
    else if (event.type === 'change') {
      if (field.type === 'multiple') {
        const inputs = [...input.closest('fieldset').querySelectorAll('input')];
        if (input.checked) for (const other of inputs) if (other !== input && (Number(input.value) === field.exclusiveValue || Number(other.value) === field.exclusiveValue)) other.checked = false;
        const values = inputs.filter(e => e.checked).map(e => Number(e.value));
        answersFor(section)[field.id] = values.length ? { status: 'answered', value: values } : D.blank();
      } else answersFor(section)[field.id] = { status: input.dataset.status, value: input.dataset.status === 'answered' ? Number(input.value) : null };
    } else return;
    if (field.inabilityLabel && !input.dataset.inability) input.closest('fieldset').querySelector('[data-inability]').checked = false;
    for (const dependent of D.fieldsFor(content, section).filter(f => f.condition)) {
      const shown = D.visible(dependent, draft[section]);
      const group = layout.querySelector(`[data-field="${dependent.id}"]`);
      group.hidden = !shown;
      if (!shown) { draft[section][dependent.id] = D.blank(); const textControl = group.querySelector('input[type="text"], textarea'); if (textControl) textControl.value = ''; }
    }
    if (section === 'pre' && editingPre) draft.preComplete = !Object.keys(D.validate(content, section, draft.pre, true)).length;
    if (section === 'post') draft.reviewReady = false;
    const current = D.validate(content, section, answersFor(section));
    errors = Object.fromEntries(Object.entries(current).filter(([id]) => id === field.id || errors[id]));
    showErrors(); save();
  }
  layout.addEventListener('input', updateAnswer); layout.addEventListener('change', updateAnswer);
  layout.addEventListener('submit', event => {
    event.preventDefault();
    if (!draft || !available()) return;
    const section = event.target.dataset.section;
    if (section.startsWith('T')) { finishTask(section, 'completed'); return; }
    errors = D.validate(content, section, draft[section], true);
    if (Object.keys(errors).length) { showErrors(); layout.querySelector('[aria-invalid="true"]')?.focus(); return; }
    if (section === 'pre') { draft.preComplete = true; editingPre = false; }
    else draft.reviewReady = true;
    save(); if (available()) go(section === 'pre' ? D.tasksComplete(draft) ? '/study/post' : taskRoute() : '/study/complete');
  });
  async function load() {
    loaded = false; loadError = false; render();
    try {
      const response = await fetch('/api/study/content', { cache: 'no-store' });
      if (!response.ok) throw new Error('Content unavailable');
      const candidate = await response.json();
      const identity = candidate.packageIdentity;
      if (candidate.packageSchemaVersion !== 2 || !identity ||
          !/^[0-9a-f]{64}$/.test(identity.digest) ||
          ['instrumentVersion', 'contentVersion', 'studyVersion'].some(key => identity[key] !== candidate[key]) ||
          !['local', 'preview', 'pilot', 'live'].includes(candidate.collectionMode) || candidate.contentVersion !== CONTENT_VERSION) throw new Error('Unsupported content');
      // A catalogue missing a required key or breaking a placeholder contract is unsupported content.
      const catalogue = window.StudyMessages.catalogue(candidate.messages), glossaryTerms = glossary(candidate.glossary);
      content = candidate; messages = catalogue; terms = glossaryTerms;
      store = D.storage(content); submission.read(); draft = store.read();
      if (submission.state?.kind === 'receipt' && submission.cleanup(() => store.discard())) draft = null;
      if (draft) { const t = draft.tasks[D.currentTask(draft)]; if (t.presented && t.status === 'pending') { t.interrupted = true; store.save(draft); } }
      loaded = true;
    } catch { loadError = true; }
    render();
  }
  function discard(route) {
    if (submission.state || submission.recoveryBlocked) { render(); return; }
    clock?.stop(true); save();
    if (store && !store.discard()) {
      if (activeTask && !document.hidden) clock?.resume();
      updateStorage(); screen.querySelector('#draft-status')?.focus(); return;
    }
    clock = null; activeTask = null;
    draft = null; errors = {}; editingPre = false; go(route, true);
  }
  layout.addEventListener('click', event => {
    const clear = event.target.closest('[data-clear]')?.dataset.clear;
    if (clear && draft) {
      const group = event.target.closest('fieldset');
      group.querySelectorAll('input').forEach(e => { e.checked = false; });
      group.querySelectorAll('select').forEach(e => { e.value = ''; });
      const section = event.target.closest('form').dataset.section;
      if (section.startsWith('T') && (draft.tasks[section].status !== 'pending' || draft.tasks[section].paused || !draft.tasks[section].presented)) return;
      answersFor(section)[clear] = D.blank();
      // Reuse dependency clearing and validation without manufacturing a choice.
      const field = content.fields.find(f => f.id === clear);
      for (const dependent of content.fields.filter(f => f.condition?.field === field.id)) {
        draft[section][dependent.id] = D.blank();
        const g = layout.querySelector(`[data-field="${dependent.id}"]`); g.hidden = true; const textControl = g.querySelector('input[type="text"], textarea'); if (textControl) textControl.value = '';
      }
      if (section === 'pre' && editingPre) draft.preComplete = !Object.keys(D.validate(content, section, draft.pre, true)).length;
      if (section === 'post') draft.reviewReady = false;
      delete errors[clear]; showErrors(); save(); return;
    }
    const action = event.target.closest('[data-action]')?.dataset.action;
    if (!action) return;
    if (action === 'retry-content') { load(); return; }
    if (!loaded) return;
    if (action === 'submit-responses' && content.submissionEnabled && draft) {
      const promise = submission.submit(draft, store.mode === 'memory'); render();
      promise.then(() => { if (submission.state?.kind === 'receipt' && submission.cleanup(() => store.discard())) draft = null; render(); }); return;
    }
    if (action === 'retry-submit' && submission.state?.kind === 'pending') {
      const promise = submission.submit(null); render(); promise.then(() => { if (submission.state?.kind === 'receipt' && submission.cleanup(() => store.discard())) draft = null; render(); }); return;
    }
    if (action === 'cleanup-receipt') { if (submission.cleanup(() => store.discard())) draft = null; render(); return; }
    // A failed discard or receipt clearance keeps the current screen and shows its issue.
    if (action === 'discard-incompatible-submission') { if (submission.discardLegacy()) load(); else render(); return; }
    if (action === 'new-study' && !submission.issue) { if (submission.clearReceipt()) { draft = null; go('/study', true); } else render(); return; }
    if (action === 'memory' && !submission.state && store.memory()) { submission.memory(); render(); return; }
    if (submission.state || submission.recoveryBlocked) return;
    if (action === 'start') {
      if (!available()) return;
      if (!draft) {
        const acknowledgements = Object.fromEntries(content.membership.consent.map(id => [id, screen.querySelector('#' + id).checked]));
        if (!Object.values(acknowledgements).every(Boolean)) { screen.querySelector('#consent-error').textContent = messageText('consent.confirm'); screen.querySelector('.acknowledgement input:not(:checked)').focus(); return; }
        try { draft = D.create(content, acknowledgements); } catch { screen.querySelector('#consent-error').textContent = messageText('consent.code-failure'); return; }
        save();
      }
      if (available()) go(maximum() === 2 ? taskRoute() : routes[maximum()]);
    }
    else if (action === 'pause-task' && activeTask) {
      const t = draft.tasks[activeTask];
      if (t.status !== 'pending' || !t.presented) return;
      if (t.paused) { t.paused = false; if (!document.hidden) clock?.resume(); }
      else { clock?.stop(true); t.paused = true; }
      save(); updateTaskStatus();
    } else if (action === 'skip-task' || action === 'unable-task') finishTask(activeTask, action === 'skip-task' ? 'skipped' : 'could_not_work_out');
    else if (action === 'edit-pre' && draft) { editingPre = true; errors = {}; go('/study/pre'); }
    else if (action === 'stop') { stopConfirming = true; render(); return; }
    else if (action === 'cancel-stop') { stopConfirming = false; returnFocusToStop = true; render(); return; }
    else if (action === 'confirm-stop') { stopConfirming = false; discard('/study/stopped'); }
    else if (action === 'decline' || action === 'restart') discard(action === 'restart' ? '/study' : '/study/declined');
    else if (action === 'memory' && store.memory()) { updateStorage(); }
    else if (action === 'retry-storage' && draft) { store.retry(draft); render(); }
  });
  document.addEventListener('click', event => {
    const target = event.target.closest('a[href^="#"]')?.getAttribute('href');
    if (!target || target.startsWith('#/')) return;
    const element = document.getElementById(target.slice(1)); if (!element) return;
    event.preventDefault(); const disclosure = element.closest('details'); if (disclosure) disclosure.open = true; element.tabIndex = -1; element.focus(); element.scrollIntoView({ block: 'start' });
  });
  document.addEventListener('keydown', event => {
    if (event.key !== 'Escape' || !stopConfirming) return;
    stopConfirming = false; returnFocusToStop = true; render();
  });
  window.addEventListener('hashchange', () => { errors = {}; render(); });
  fetch('/api/release', { cache: 'no-store' }).then(r => r.ok ? r.json() : null).then(release => {
    if (release) {
      const label = document.querySelector('#app-version');
      label.textContent = release.version === 'development' ? 'Development' : `v${release.version}`;
      label.title = release.revision;
    }
  }).catch(() => {});
  await load();
})();
