import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { webcrypto } from 'node:crypto';
import vm from 'node:vm';
const context={window:{},crypto:webcrypto,structuredClone,TextEncoder,AbortSignal,fetch};
vm.createContext(context);
for(const file of ['study-draft.js','study-submit.js']) vm.runInContext(await readFile(new URL('../src/frontend/'+file,import.meta.url),'utf8'),context);
const D=context.window.StudyDraft,S=context.window.StudySubmit;
const content=JSON.parse(await readFile(new URL('../src/backend/evaluation/participant-content.json',import.meta.url)));
const d=D.create(content,Object.fromEntries(content.fields.filter(f=>f.id.startsWith('C')).map(f=>[f.id,true])));
d.pre.P1={status:'answered',value:1};d.preComplete=d.p13Locked=d.reviewReady=true;
for(const t of Object.values(d.tasks)){t.status='completed';t.started=true;t.durationMs=123.6;}
let values=new Map(),fail=false;
const storage={getItem:k=>values.get(k)||null,setItem(k,v){if(fail)throw Error();values.set(k,v);},removeItem(k){if(fail)throw Error();values.delete(k);}};
let calls=[],lost=true;
const send=async(url,options)=>{calls.push(options.body);const p=JSON.parse(options.body);if(lost)throw Error('Lost acknowledgement');return {ok:true,status:200,json:async()=>({receiptId:'synthetic-receipt',participantCode:p.participantCode,submissionId:p.submissionId,studyVersion:p.studyVersion})};};
const checks=[];
let s=S.controller(()=>storage,send);
await s.submit(d);assert.equal(s.state.kind,'pending');checks.push('Uncertain acknowledgement retains frozen envelope');
assert.equal(JSON.parse(calls[0]).tasks[0].durationMs,124);checks.push('Fractional E5 duration rounded once');
d.pre.P1.value=2;
s=S.controller(()=>storage,send);s.read();await s.submit(d);assert.equal(calls[0],calls[1]);checks.push('Refresh and edited original cannot alter retry payload or ID');
lost=false;await s.submit(d);assert.equal(s.state.kind,'receipt');assert.equal(calls[0],calls[2]);checks.push('Identical retry receives receipt');
fail=true;assert.equal(s.cleanup(()=>true),false);assert.ok(s.issue);checks.push('Receipt cleanup failure is explicit');
fail=false;assert.equal(s.cleanup(()=>true),true);assert.ok(!values.get(S.KEY).includes('answers'));checks.push('Acknowledged payload replaced with minimal receipt');
s.clearReceipt();fail=true;s=S.controller(()=>storage,send);const before=calls.length;await s.submit(d);assert.equal(calls.length,before);assert.equal(s.state,null);checks.push('Failed retry-copy storage sends nothing');
await s.submit(d,true);assert.equal(s.state.kind,'receipt');checks.push('Explicit memory-only submission supported');
fail=false;values.clear();let release;const gate=new Promise(r=>release=r);let count=0;
s=S.controller(()=>storage,async(...args)=>{count++;await gate;return send(...args);});const first=s.submit(d);await s.submit(d);assert.equal(count,1);release();await first;checks.push('Double click produces one in-flight request');
values.clear();s=S.controller(()=>storage,send);d.tasks.T0.durationMs=86400001;await s.submit(d);assert.equal(s.state,null);checks.push('Oversized duration retained locally without an invalid network attempt');
console.log(`${checks.length} submission checks pass`);
