import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { webcrypto } from 'node:crypto';
import vm from 'node:vm';
const context={window:{},crypto:webcrypto,structuredClone,TextEncoder,AbortSignal,fetch};
vm.createContext(context);
for(const file of ['study-draft.js','study-submit.js','study-messages.js']) vm.runInContext(await readFile(new URL('../src/frontend/'+file,import.meta.url),'utf8'),context);
const D=context.window.StudyDraft,S=context.window.StudySubmit;
const content=JSON.parse(await readFile(new URL('../src/backend/evaluation/participant-package-v2.json',import.meta.url))).content;
// Issues are compiled message references; the catalogue supplies their wording.
const say=reference=>context.window.StudyMessages.catalogue(content.messages).text(reference);
const studyView=await readFile(new URL('../src/frontend/study.js',import.meta.url),'utf8');
const d=D.create(content,Object.fromEntries(content.membership.consent.map(id=>[id,true])));
d.pre.P1={status:'answered',value:1};d.preComplete=d.p13Locked=d.reviewReady=true;
for(const t of Object.values(d.tasks)){t.status='completed';t.presented=true;t.durationMs=123.6;}
let values=new Map(),fail=false;
const storage={getItem:k=>values.get(k)||null,setItem(k,v){if(fail)throw Error();values.set(k,v);},removeItem(k){if(fail)throw Error();values.delete(k);}};
let calls=[],lost=true;
const send=async(url,options)=>{calls.push(options.body);const p=JSON.parse(options.body);if(lost)throw Error('Lost acknowledgement');return {ok:true,status:200,json:async()=>({receiptId:'synthetic-receipt',participantCode:p.participantCode,submissionId:p.submissionId,studyVersion:p.studyVersion})};};
const checks=[];
assert.equal(S.KEY, 'irexplorer.submission.v3');
assert.notEqual(S.KEY, 'irexplorer.submission.v2');
assert.notEqual(S.KEY, 'irexplorer.study.submission.e6');
checks.push('Pending submissions use the versioned submission recovery key');
let s=S.controller(()=>storage,send);
await s.submit(d);assert.equal(s.state.kind,'pending');assert.ok(values.has(S.KEY));
assert.equal(say(s.issue),content.messages['submission.uncertain'].replace('{error}','Lost acknowledgement'));checks.push('Uncertain acknowledgement retains the frozen submission under the new key with compiled retry guidance');
assert.equal('presented' in JSON.parse(calls[0]).tasks[0],false);
assert.equal('setupReached' in JSON.parse(calls[0]).tasks[0],false);
assert.equal(JSON.parse(calls[0]).tasks[0].durationMs,124);checks.push('Fractional E5 duration rounded once');
d.pre.P1.value=2;
s=S.controller(()=>storage,send);s.read();await s.submit(d);assert.equal(calls[0],calls[1]);checks.push('Refresh and edited original cannot alter retry payload or ID');
lost=false;await s.submit(d);assert.equal(s.state.kind,'receipt');assert.equal(calls[0],calls[2]);checks.push('Identical retry receives receipt');
fail=true;assert.equal(s.cleanup(()=>true),false);assert.equal(say(s.issue),content.messages['cleanup.retry-save']);
fail=false;assert.equal(s.cleanup(()=>false),false);assert.equal(say(s.issue),content.messages['cleanup.retry-draft']);checks.push('Receipt cleanup failures say an answer copy may remain');
fail=false;assert.equal(s.cleanup(()=>true),true);assert.ok(!values.get(S.KEY).includes('answers'));checks.push('Acknowledged payload replaced with minimal receipt');
s.clearReceipt();fail=true;s=S.controller(()=>storage,send);const before=calls.length;await s.submit(d);assert.equal(calls.length,before);assert.equal(s.state,null);assert.equal(say(s.issue),content.messages['submission.retry-save-failed']);checks.push('Failed retry-copy storage sends nothing');
await s.submit(d,true);assert.equal(s.state.kind,'receipt');checks.push('Explicit memory-only submission supported');
fail=false;values.clear();let release;const gate=new Promise(r=>release=r);let count=0;
s=S.controller(()=>storage,async(...args)=>{count++;await gate;return send(...args);});const first=s.submit(d);await s.submit(d);assert.equal(count,1);release();await first;checks.push('Double click produces one in-flight request');
values.clear();s=S.controller(()=>storage,send);d.tasks.T0.durationMs=86400001;await s.submit(d);assert.equal(s.state,null);assert.equal(say(s.issue),content.messages['submission.limit']);checks.push('Oversized duration retained locally without an invalid network attempt');
values.clear();values.set('irexplorer.submission.v2', JSON.stringify({kind:'pending',submission:{submissionId:'old',participantCode:'old-participant',instrumentVersion:'v0.6'}}));
s=S.controller(()=>storage,send);s.read();assert.equal(s.recoveryBlocked,true);assert.equal(s.legacyPending,true);
assert.equal(say(s.issue),content.messages['recovery.incompatible']);assert.equal(s.legacyParticipantCode, 'old-participant');assert.equal(s.discardLegacy(),true);assert.equal(values.has('irexplorer.submission.v2'),false);
assert.match(studyView,/'actions\.discard-incompatible'/);assert.match(studyView,/submission\.discardLegacy\(\)/);
checks.push('v0.6 pending submission is offered an explicit incompatible-draft discard path');
values.clear();const frozen={...JSON.parse(calls[0]),submissionId:webcrypto.randomUUID(),instrumentVersion:'v0.10',contentVersion:'v0.10-preview-1',studyVersion:'v0.10-synthetic-1'};
frozen.consent={...frozen.consent,version:frozen.contentVersion};values.set(S.KEY,JSON.stringify({kind:'pending',submission:frozen}));
let committed=false;const upgradeCalls=[];
const upgraded=async(url,options)=>{upgradeCalls.push(options.body);const p=JSON.parse(options.body);return committed
  ?{ok:true,status:200,json:async()=>({receiptId:'original-receipt',participantCode:p.participantCode,submissionId:p.submissionId,studyVersion:p.studyVersion})}
  :{ok:false,status:422,json:async()=>({error:{code:'invalid_submission',message:'Check consent, P1, versions, task outcomes, and answer limits. No answers were changed.'}})};};
s=S.controller(()=>storage,upgraded);s.read();assert.equal(s.recoveryBlocked,false);await s.submit(null);
assert.equal(s.state.kind,'pending');assert.deepEqual(JSON.parse(values.get(S.KEY)).submission,frozen);assert.equal(say(s.issue),content.messages['submission.uncertain'].replace('{error}','Check consent, P1, versions, task outcomes, and answer limits. No answers were changed.'));
checks.push('Rejected uncommitted older-release submission stays frozen without a receipt');
committed=true;s=S.controller(()=>storage,upgraded);s.read();await s.submit(null);
assert.equal(s.state.kind,'receipt');assert.equal(s.state.receipt.receiptId,'original-receipt');
assert.equal(new Set(upgradeCalls).size,1);assert.deepEqual(JSON.parse(upgradeCalls[0]),frozen);
checks.push('Committed older-release submission recovers its receipt with the same frozen submission and ID after an upgrade');
values.clear();values.set(S.KEY,'{broken');s=S.controller(()=>storage,send);s.read();assert.equal(s.recoveryBlocked,true);assert.equal(say(s.issue),content.messages['recovery.unreadable']);
checks.push('Corrupt submission recovery stays explicit with compiled guidance');
const refused=async()=>({ok:false,status:503,json:async()=>({})}),foreign=async(url,o)=>({ok:true,status:200,json:async()=>({receiptId:'r',participantCode:'other',submissionId:JSON.parse(o.body).submissionId,studyVersion:'x'})});
values.clear();d.tasks.T0.durationMs=1;s=S.controller(()=>storage,refused);await s.submit(d);assert.equal(s.state.kind,'pending');
assert.equal(say(s.issue),content.messages['submission.uncertain'].replace('{error}',content.messages['submission.no-receipt']));
s=S.controller(()=>storage,foreign);s.read();await s.submit(null);assert.equal(s.state.kind,'pending');
assert.equal(say(s.issue),content.messages['submission.uncertain'].replace('{error}',content.messages['submission.invalid-receipt']));
checks.push('No receipt is shown without a matching durable server receipt');
values.clear();const unsupportedFrozen={...frozen,submissionId:webcrypto.randomUUID()};values.set(S.KEY,JSON.stringify({kind:'pending',submission:unsupportedFrozen}));
const unsupportedCalls=[];
const unsupported=async(url,options)=>{unsupportedCalls.push(options.body);return {ok:false,status:422,json:async()=>({error:{code:'unsupported_instrument',message:'Check consent, P1, versions, task outcomes, and answer limits. No answers were changed.'}})};};
s=S.controller(()=>storage,unsupported);s.read();await s.submit(null);
assert.equal(s.state.kind,'pending');assert.deepEqual(JSON.parse(values.get(S.KEY)).submission,unsupportedFrozen);
assert.equal(s.recoveryBlocked,true);assert.equal(s.legacyPending,true);assert.equal(s.legacyParticipantCode,unsupportedFrozen.participantCode);
assert.equal(say(s.issue),content.messages['recovery.incompatible']);
await s.submit(null);assert.equal(unsupportedCalls.length,1);
assert.match(studyView,/submission\.state && !submission\.recoveryBlocked\) html = submissionHtml\(\)/);
checks.push('Unsupported-instrument rejection keeps the frozen submission and reports incompatibility with compiled guidance, without a receipt or retry claim');
assert.equal(s.discardLegacy(),true);assert.equal(values.has(S.KEY),false);assert.equal(s.state,null);assert.equal(s.recoveryBlocked,false);
checks.push('Incompatible frozen submission is removed only by the explicit discard');
console.log(`${checks.length} submission checks pass`);
